language: python
python:
- '3.6'
- '3.7'
install:
- export VERSION=$(sed 's/^v//' <<<"${TRAVIS_TAG:-0.0.0+$(sed 's^[/_-]^.^g' <<<$TRAVIS_BRANCH)}")
- find . -type f -exec sed -i "s/{{VERSION}}/${VERSION}/g" {} \;
- pip install tox
script: tox
deploy:
  provider: pypi
  username: "__token__"
  password:
    secure: "g+xvLDSGPft/PFkRVooVem2IMh4+jckq/EKNguYRgXgn1iL1ro2lLWxZ54LCsndHTuHgLXWj2zxpIakDdm9faNLV7mvyV8kxVOZu8aSazEDIwtagKEidEXFcIz9j0rXS+OuV2FqZWvbnf4x9fOxVGT4V06doLq5a+VTnygTHhfvmxExhfgbG/eGgKJNfHoCjjXS49T2cBHQa/CdmtOqtEbCeJ/MBeeF+yf1tc3xq8PxdoQ4hZFpGMO1aF/O6ENOWfpBXIm8XFlzLHQA4hN0q4EkC5+kSa5/t476rXKJ3iN29oCD9yQIFUHEBamdz/QYQUldE5qJ41NEjBlI2xgBDFWXDexgDDcfSDStQ/RfFsn6Ydu9XmLfwhzNVS9I0LEFvzrpNCkZuQvUcFRAfEK5Hz6m2+Er6395L/TUxO0JkZGoMsTqkCTnsYHQ4XY2uw518T2vwyD0g0PZMymm75ADkrKA9kv+jRx8QM7pFnW5IMF3CaHMI9YBd4zLEnqeEXE7p3MhyrJhMt3f4cZ6bXnTM3itmEMW3M11hdHnyzgbP9M8xGEvj7PHCuU6mZINpsmEzud+q12Q1wzS2zcqLdPCR8kjkYg/6ZrfbCPKAXG5fnXiOAJi9ZN5iJErGhyvUW63fpm3DYmkMhANyx68hSrhA+YFbBiZ1MhISmsOgX8taqRI="
  skip_cleanup: true
  skip_existing: true
  on:
    tags: true
